config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # root
  root 'sessions#new'

  get 'users/new'
  # products
 
  get "products/" => "products#index", as:"products" 
  get 'product/new' => "products#new", as:"product_new"
  post 'products/' => "products#create"
  get 'product/:id' => "products#show", as:"product"
  get 'product/:id/edit/' => "products#edit", as:"product_edit"
  patch 'product/:id/edit/' => "products#update"
  delete 'products/:id/delete' => "products#destroy",as:"product_delete"
  get 'products/:id/delete' => "products#destroy"
  patch 'stopbid/:id' => "products#stopbid", as:"stop"
  get 'stopbid/:id/'  => "products#stopbid"
  # bidders
  get 'send-bid/:id' => 'bidders#new', as:"bid"
  post 'send-bid/:id' => 'bidders#create'

  # register
  get "register/" => "users#new", as:"user"
  post "register/" => "users#create"
  # view profile
  get "user/" => "users#show", as:"profile"
  # login
  get 'login/' => "sessions#new", as:"login"
  post 'login/' => "sessions#create"
  delete 'logout/' => "sessions#destroy"
  get 'logout/' => "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :admin_user
  has_many :bids, dependent: :delete_all
  # check if the post is created by the admin
  # attr_accessor:create_by_admin
  # before_save:set_created_by_admin_flag
  # def set_created_by_admin_flag
  #   self.create_by_admin = user&.is_admin?
  # end


  # check if the bidder is uniq and cannot be repeated
  def bids_sum
    bids.sum(:bid_value)
  end
  
  def winner
    (bidding_expiration <= DateTime.now || (stop_switch && bids.nil?)) ? "₱#{bids_sum}" : "None"
  end
  # it must be present
  validates :product_name,presence:true,length: { maximum: 500 }
  validates :description,presence:true
  # it must be present and it must greather than and equal zero
  validates :lowest_allowable_bid,presence:true,
      numericality:{greater_than_or_equal_to:0,only_integer:true}
  # it must be present and it must greather than and equal zero
  validates :starting_bid_price,presence:true,
      numericality:{greater_than_or_equal_to:0,only_integer:true}

# it must be present and it must be
  validates :bidding_expiration,presence:true, timeliness: { 
    on_or_after: lambda{DateTime.now}, 
    type: :datetime,between:[DateTime.now,1.year.from_now] }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # check if the user is logged_in
  before_action :require_login

  def index
    @products = Product.where(stop_switch:false).order(created_at: :desc)
  end

  # show the product and 
  def show
    @product = Product.find_by(id: params[:id])
    if @product
      @bids = @product.bids.order(created_at: :desc)
    end
  
  end
 


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with model:@product,url:setup,data:{turbo:false} do |f| %>

     <%= render partial:"layouts/error_message",locals:{objects:@product} %>
    <div class="mb-3">   
         <%= f.label :"Product name : " %>
         <%= f.text_field :product_name,class:"form-control"%>
    </div>
    <div class="mb-3">
          <%= f.label :"Add Photo : ",class:"d-block"%>
          <%= f.file_field :image,accept:"image/*" %>
    </div>
    <div class="mb-3">   
         <%= f.label :"Description : " %>
         <%= f.text_field :description,class:"form-control"%>
    </div>
    
    <div class="mb-3">   
         <%= f.label :"Lowest allowable bid : " %>
         <%= f.number_field :lowest_allowable_bid,class:"form-control" %>
    </div>
    
    <div class="mb-3">   
         <%= f.label :"Starting Bid Price : " %>
         <%= f.number_field :starting_bid_price,class:"form-control" %>
    </div>
    
    <div class="mb-3">
        <%= f.label :"Bidding Expiration : " %>
         <%= f.datetime_field :bidding_expiration,class:"form-control",max:1.year.from_now %>
    </div>
    <input type="hidden"name="product[user_id]" value=<%= current_user.id %>>
     
   <div class="mb-3">
        <%= f.submit yield(:button),class:"btn btn-success" %>
   </div>
    
<% end %>

app/views/products/edit.html.erb
<% provide(:title,"Edit Bid") %>
<% provide(:button,"Edit Auction") %>
<h1>Edit Bid</h1>


<%= render partial:"form",locals:{setup:product_edit_path(@product)} %>

app/views/products/index.html.erb
<% provide(:title,"") %>
<h1>Auction</h1>

<table class="table table-striped text-center">
    <thead>
        <tr>
            <td scope="col">Image</td>
            <td scope="col">Product Name</td>
            <td scope="col">Description</td>
            <td scope="col">Lowest Allowable Bid</td>
            <td scope="col">Starting Bid Price</td>
            <td scope="col">Bidding Expiration</td>
            <td scope="col">Current Lowest Bid</td>
            <td scope="col">Action</td>
        </tr>
    </thead>
    <tbody>
        
        <% @products.each do |product| %>
        <tr>
            <td><%= !product.image.nil? ? cl_image_tag(product.image , :width=>200, :crop=>"fill"):cl_image_tag("no_rpqcih", :width=>200, :crop=>"fill") %></td>
            <td><%= product.product_name %></td>
            <td><%= product.description %></td>
            <td>₱<%= number_with_delimiter(product.lowest_allowable_bid) %></td>
            <td>₱<%= number_with_delimiter(product.starting_bid_price) %></td>
            <td><%= product.bidding_expiration.strftime('%Y-%m-%d %I:%M %p') %></td>
            <td> <%= product.bids.empty? ? "None" : "₱#{number_with_delimiter(product.bids[-1].bid_value)}"  %></td>
            <td>
                <div class="row">
        
                 <%# check if the auction is expired %>
                    <% if DateTime.now < product.bidding_expiration && !product.stop_switch%>
                        <%= link_to "Send Bid",bid_path(product),class:"btn btn-primary mb-2"%>
                    <% else %>
                        <%= link_to "Closed","#",class:"btn btn-warning disabled-link mb-2"%>   
                    <% end %>

                    <%= link_to "Show Product",product_path(product),class:"btn btn-secondary mb-2"%>
                    <% if DateTime.now >= product.bidding_expiration || product.stop_switch %>
                        Winner: <%= product.bids.empty? ? "None" : product.bids[-1].user.full_name %>
                        
                    <% end %>
            
                
                </div>
                

                
            </td>
        </tr>   
        <% end %>
    
    </tbody>
</table>
<% if Product.count == 0 %>
    <h2 class="text-center">No Auction</h2>
<% end %>

app/views/products/new.html.erb
<% provide(:title,"Create Bid") %>
<% provide(:button,"Create Auction") %>
<h1>Create Bid</h1>


<%= render partial:"form",locals:{setup:products_path}%>

app/views/products/show.html.erb
<% provide(:title,"Show Auction") %>

<h1>Product: <%= @product.product_name %></h1>
<%= !@product.image.nil? ? cl_image_tag(@product.image , :width=>200, :crop=>"fill"):cl_image_tag("no_rpqcih", :width=>200, :crop=>"fill") %>

<p><b>Description:</b> <%= @product.description %></p>
<p><b>Lowest allowable bid:</b> <%= @product.lowest_allowable_bid %></p>
<p><b>Starting bid price:</b> <%= @product.starting_bid_price %></p>
<p><b>Bidding expiration:</b> <%= @product.bidding_expiration.strftime('%Y-%m-%d %I:%M %p') %></p>

<h3>Lastest Bid :</h3>

<% @bids.each do |product| %>
    <p><b>Name: </b><%= product.user.full_name %></p>
    <p><b>Bid: </b><%= product.bid_value %></p>
    <p><b>Created: </b><%= product.created_at.strftime('%Y-%m-%d %I:%M %p') %></p>
    <hr>
<% end %>

<% if @bids.count == 0 %>
<hr class="divider">
    <h4 class="text-center">No Bidders</h4>
<% end %>