config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # root
  root 'sessions#new'

  get 'users/new'
  # products
 
  get "products/" => "products#index", as:"products" 
  get 'product/new' => "products#new", as:"product_new"
  post 'products/' => "products#create"
  get 'product/:id' => "products#show", as:"product"
  get 'product/:id/edit/' => "products#edit", as:"product_edit"
  patch 'product/:id/edit/' => "products#update"
  delete 'products/:id/delete' => "products#destroy",as:"product_delete"
  get 'products/:id/delete' => "products#destroy"
  patch 'stopbid/:id' => "products#stopbid", as:"stop"
  get 'stopbid/:id/'  => "products#stopbid"
  # bidders
  get 'send-bid/:id' => 'bidders#new', as:"bid"
  post 'send-bid/:id' => 'bidders#create'

  # register
  get "register/" => "users#new", as:"user"
  post "register/" => "users#create"
  # view profile
  get "user/" => "users#show", as:"profile"
  # login
  get 'login/' => "sessions#new", as:"login"
  post 'login/' => "sessions#create"
  delete 'logout/' => "sessions#destroy"
  get 'logout/' => "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_error_message.html.erb
<% if objects.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(objects.errors.count, "error") %>.
    <ul>
      <% objects.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  </div>
<% end %>



app/views/layouts/_flash_message.html.erb

<% flash.each do |type, msg| %>
  <div class="container mt-2">
    <div class="alert alert-<%= type %>">
  
      <%= msg %>
    
    </div>
  </div>
  
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    
    <% if logged_in? %>
         <%= link_to "BidDash",products_path,class:"navbar-brand" %>
    <% else %>
         <%= link_to "BidDash",login_path,class:"navbar-brand" %>
    <% end %>
    
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
            <li class="nav-item">
              <%= link_to "Home",products_path,class:"nav-link" %>
            </li>
            
        <% end %>
      </ul>
      <ul class="d-flex navbar-nav ms-auto mb-2 mb-lg-0">
          
          <% if logged_in? %>
          
          <% if current_user %>
            <li class="nav-item mx-3"> 
                <%= link_to @current_user.full_name, profile_path,class:"nav-link" %>
            </li> 
          <% end %>
            <li class="nav-item mx-3"> 
                <%= link_to 'Logout', logout_path, method: :delete, :class => 'btn btn-outline-secondary',:onclick => "return confirm('Are you sure you want to delete this post?')" %>
            </li>
          <% else %>
             <li class="nav-item">
                <%= link_to "Login",login_path,class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Up",user_path,class:"nav-link" %>
            </li>
          <% end %>
          
            
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= base_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_importmap_tags  %>
    
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    
   </head>

  <body>
    <%= render partial:"layouts/navbar" %>
    <%= render partial:"layouts/flash_message" %>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>